# Generated by Django 4.1.2 on 2022-10-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dishreservation_dishdailyavailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dishdailyavailability',
            unique_together={('dish', 'day')},
        ),
    ]
