version: '3.7'
services:

  load_balancer:
    container_name: microservices_mr_sandwich_load_balancer
    hostname: load_balancer
    networks:
      - microservices_mr_sandwich
    build:
      context: ./load_balancer
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DOMAIN=mr_sandwich.localhost
      - LOG_LEVEL=warn

  auth:
    container_name: microservices_mr_sandwich_auth
    hostname: auth
    networks:
      - microservices_mr_sandwich
    build:
      context: ./auth
    environment:
      - WSGI_LOG_LEVEL=warn
      - APP_LOG_LEVEL=WARNING
      - DATABASE_DSN=postgres://postgres:postgres@auth_db:5432/auth
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq//

  auth_worker:
    container_name: microservices_mr_sandwich_auth_worker
    networks:
      - microservices_mr_sandwich
    build:
      context: ./auth
      dockerfile: worker.Dockerfile
    environment:
      - APP_LOG_LEVEL=WARNING
      - DATABASE_DSN=postgres://postgres:postgres@auth_db:5432/auth
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq//

  auth_db:
    image: postgres:14.4-alpine
    container_name: microservices_mr_sandwich_auth_db
    hostname: auth_db
    networks:
      - microservices_mr_sandwich
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth

  food_factory:
    container_name: microservices_mr_sandwich_food_factory
    hostname: food_factory
    networks:
      - microservices_mr_sandwich
    build:
      context: ./food_factory
    environment:
      - WSGI_LOG_LEVEL=info
      - APP_LOG_LEVEL=DEBUG
      - DATABASE_DSN=postgres://postgres:postgres@food_factory_db:5432/food_factory
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq//
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

  food_factory_db:
    image: postgres:13.8-alpine
    container_name: microservices_mr_sandwich_food_factory_db
    hostname: food_factory_db
    networks:
      - microservices_mr_sandwich
    ports:
      - "5434:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=food_factory

  web_store_cart:
    container_name: microservices_mr_sandwich_web_store_cart
    hostname: web_store_cart
    networks:
      - microservices_mr_sandwich
    build:
      context: ./web_store_cart
    environment:
      - WSGI_LOG_LEVEL=info
      - APP_LOG_LEVEL=debug
      - DATABASE_DSN=postgresql://postgres:postgres@web_store_cart_db:5432/web_store_cart
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq//

  web_store_cart_db:
    image: postgres:14.4-alpine
    container_name: microservices_mr_sandwich_web_store_cart_db
    hostname: web_store_cart_db
    networks:
      - microservices_mr_sandwich
    ports:
      - "5435:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web_store_cart

  rabbitmq:
    image: rabbitmq:3.11.2-management
    container_name: microservices_mr_sandwich_rabbitmq
    hostname: rabbitmq
    networks:
      - microservices_mr_sandwich

#  central_log:
#    image: rsyslog/syslog_appliance_alpine
#    container_name: microservices_mr_sandwich_central_log
#    hostname: central_log
#    networks:
#      - microservices_mr_sandwich
#    volumes:
#      - central_logs:/logs
#    environment:
#      - TZ=Europe/Warsaw
#      - FWD_TO_HOST=central_log


networks:
  microservices_mr_sandwich:
    name: microservices_mr_sandwich

volumes:
  central_logs:
  db_auth:
  db_food_factory:
  db_web_store_cart:
