version: '3.7'
services:

  load_balancer:
    container_name: microservices_mr_sandwich_load_balancer
    networks:
      - microservices
    build:
      context: ./load_balancer
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

  auth:
    container_name: microservices_mr_sandwich_auth
    networks:
      - microservices
    build:
      context: ./auth

  auth_worker:
    container_name: microservices_mr_sandwich_auth_worker
    networks:
      - microservices
    build:
      context: ./auth
      dockerfile: worker.Dockerfile

  food_factory:
    container_name: microservices_mr_sandwich_food_factory
    networks:
      - microservices
    build:
      context: ./food_factory
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

  rabbitmq:
    image: rabbitmq:3.11.2-management
    container_name: microservices_mr_sandwich_rabbitmq
    networks:
      - microservices


#  web_store:
#    container_name: microservices_mr_sandwich_web_store
#    build:
#      context: ./web_store
#    volumes:
#      - ./:/opt
#
#  delivery:
#    container_name: microservices_mr_sandwich_delivery
#    build:
#      context: ./delivery
#    volumes:
#      - ./:/opt
networks:
  microservices:
    name: microservices