version: '3.7'
services:

  load_balancer:
    container_name: microservices_mr_sandwich_load_balancer
    hostname: load_balancer
    networks:
      - microservices_mr_sandwich
    build:
      context: ./load_balancer
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

  auth:
    container_name: microservices_mr_sandwich_auth
    hostname: auth
    networks:
      - microservices_mr_sandwich
    build:
      context: ./auth

  auth_worker:
    container_name: microservices_mr_sandwich_auth_worker
    networks:
      - microservices_mr_sandwich
    build:
      context: ./auth
      dockerfile: worker.Dockerfile

  food_factory:
    container_name: microservices_mr_sandwich_food_factory
    hostname: food_factory
    networks:
      - microservices_mr_sandwich
    build:
      context: ./food_factory
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

  rabbitmq:
    image: rabbitmq:3.11.2-management
    hostname: rabbitmq
    container_name: microservices_mr_sandwich_rabbitmq
    networks:
      - microservices_mr_sandwich

  web_store_cart:
    container_name: microservices_mr_sandwich_web_store_cart
    hostname: web_store_cart
    networks:
      - microservices_mr_sandwich
    build:
      context: ./web_store_cart
#
#  delivery:
#    container_name: microservices_mr_sandwich_delivery
#    build:
#      context: ./delivery
#    volumes:
#      - ./:/opt
networks:
  microservices_mr_sandwich:
    name: microservices_mr_sandwich