version: '3.7'
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/opt/scripts

  db_sql:
    container_name: db_sql
    build:
      context: .
    volumes:
      - ./:/opt
