version: '3.7'
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: databases_sql_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/opt/scripts

  app:
    container_name: databases_sql_app
    build:
      context: .
    volumes:
      - ./:/opt
