global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "web_store_cart"
    metrics_path: "/web_store_cart/metrics"
    static_configs:
      - targets: ["host.docker.internal:8002"]
